[build]
command = "npm run build --production && cp public/manifest.webmanifest www/manifest.webmanifest && cp public/icons www/icons -r"
publish = "www"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
from   = "/*"
to     = "/index.html"
status = 200
